### ISSUE TITLE
http协议的webui无法接入麦克风（确认插入了麦克风），需要怎么设置浏览器或者改用https？Chrome浏览器

### ISSUE THREAD

**Issue by yuanmaitian** [FunAudioLLM/SenseVoice#10]
![微信图片_20240706150348](https://github.com/FunAudioLLM/SenseVoice/assets/39802447/f292147e-c376-4214-a653-008ec9bab843)

**Comment by YunzhaoLu** [comment]
For chrome browser, type "chrome://flags/" in address, and enable the insecure origin of the "http" site.
