### ISSUE TITLE
请问情绪识别功能怎么使用，有相应的推理脚本吗

### ISSUE THREAD

**Issue by HeJinLing** [FunAudioLLM/SenseVoice#11]
加载模型参数文件，会报错需要tokenizer的token_list（参数文件中没有，且没有对应的输入格式）
另外SER入参应该在何处送入呢

**Comment by joseph16388** [comment]
顶！

**Comment by LauraGPT** [comment]
What's your problem?

**Comment by gaochangfeng** [comment]
默认推理参数下模型输出的前三个token分别为语种、情感和事件，不需要专门配置
