### ISSUE TITLE
是否能支持nodeJS调用，比如nodeJS版本的ONNX

### ISSUE THREAD

**Issue by zhouzhili** [FunAudioLLM/SenseVoice#117]
#### What is your question?
目前网站使用nextjs开发的，想集成SenseVoice，看到目前已经有Python版本的funasr-onnx，请问是否有计划开发nodeJS版本的onnx？

**Comment by csukuangfj** [comment]
https://github.com/k2-fsa/sherpa-onnx/blob/master/nodejs-addon-examples/test_asr_non_streaming_sense_voice.js

可以试试这个例子
```
npm i sherpa-onnx-node
```
然后参考https://k2-fsa.github.io/sherpa/onnx/sense-voice/pretrained.html
下载模型，即可运行

支持 windows, linux, macos 上的 nodejs 里面调用.

---

下面的例子是实在 WebAssembly 里面，调用 sense voice 模型
https://github.com/k2-fsa/sherpa-onnx/blob/master/nodejs-examples/test-offline-sense-voice.js
