### ISSUE TITLE
【请教】数据集的各个字段解释

### ISSUE THREAD

**Issue by LateLinux** [FunAudioLLM/SenseVoice#125]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

## ❓ Questions and Help

计划标注部分数据，但不是很明白各个字段的含义，特请教。

- #### 已基本搞明白的有：

"key"、"source"、"target"、"target_len"、“text_language”、“emo_target”

- #### 不太明白的有：

"source_len"，issue里有解释是“帧”，对应“10ms”，但个别已有数据集中也对不上，所以对“有效音频信息”的理解也许有偏差，求解释。

- #### 完全没有找到信息的有：

“event_target”、“with_or_wo_itn”

感谢感谢！

**Comment by gaochangfeng** [comment]
“event_target”: 音频事件，“with_or_wo_itn”：是否对文本进行正则化（添加标点、文字变数字）
