### ISSUE TITLE
每次cpu调用后内存都会增加

### ISSUE THREAD

**Issue by Eoous** [FunAudioLLM/SenseVoice#127]
仅通过cpu调用，每次进行inference()都会增加内存，并且不会下降

**Comment by LauraGPT** [comment]
Bug has been fixed. Please update the code or funasr-1.1.8

**Comment by Eoous** [comment]
更新代码后这个问题还是可以复现

**Comment by NBStarry** [comment]
+1

**Comment by Katock-Cricket** [comment]
+1，只要一次性推理超过8个左右音频，内存占用爆炸式增加到40多G

**Comment by garment-chan** [comment]
请问现在有修复吗？
