### ISSUE TITLE
导出的onnx 模型比 正常的模型推理慢

### ISSUE THREAD

**Issue by DuBaiSheng** [FunAudioLLM/SenseVoice#132]
使用export 导出的onnx格式的模型，并使用SenseVoiceSmall加载，批次推理的时长，比原本使用AutoModel加载的原始模型 要慢7倍。是什么原因呢，都是使用GPU加载推理。

**Comment by LauraGPT** [comment]
![image](https://github.com/user-attachments/assets/84da3933-836d-49a7-952d-707979b44803)

**Comment by Nicksooooo** [comment]
我 也有这个问题，每次加载新的语音，推理时间都很长，cpu的话没事
