### ISSUE TITLE
无法识别，返回是空

### ISSUE THREAD

**Issue by JosenJin** [FunAudioLLM/SenseVoice#135]
已经正常部署，运行的中文示例，但是返回为什么是空？
![image](https://github.com/user-attachments/assets/5e527a8f-ab13-4c5f-ab1f-d320f05d468a)
![image](https://github.com/user-attachments/assets/068589c9-8368-4446-974b-e7db6f2b4311)

**Comment by LauraGPT** [comment]
gradio的问题，过一会再点击start

**Comment by lwcode** [comment]
解决了, 把之前安装的funasr环境全删除, 重新conda一个环境, 然后`pip install -r requirements.txt`安装所需环境就可以, 就能正常工作了.
