### ISSUE TITLE
onnx模型在输入多段音频时，有些asr的结果为空，有什么解决的办法吗

### ISSUE THREAD

**Issue by foolishcqx** [FunAudioLLM/SenseVoice#142]
请问如何解决asr结果为空的问题？

**Comment by LauraGPT** [comment]
What's your problem?

**Comment by foolishcqx** [comment]
> What's your problem?

When the onnx model inputs multiple audio segments, some ASR results are empty. Is there any solution

**Comment by foolishcqx** [comment]
have slove
