### ISSUE TITLE
使用funasr推理时文字结果中带<|zh|><|NEUTRAL|><|Speech|><|woitn|>这样的标签，有没有办法去除掉？

### ISSUE THREAD

**Issue by Coder0015** [FunAudioLLM/SenseVoice#17]

**Comment by gaotiexinqu** [comment]
我也遇到了同样的问题

**Comment by rookie0607** [comment]
sed 's/<[^>]*>//g'

**Comment by Lizerui9926** [comment]
https://github.com/FunAudioLLM/SenseVoice?tab=readme-ov-file#method-2

**Comment by Lizerui9926** [comment]
Please update funasr and refer to the [Inference Method 2](https://github.com/FunAudioLLM/SenseVoice?tab=readme-ov-file#method-2)

**Comment by 123WT-LANG** [comment]
怎么解决的

**Comment by 123WT-LANG** [comment]
How was it solved?
