### ISSUE TITLE
[Tips] The version of FunASR should be updated.

### ISSUE THREAD

**Issue by SapphireLab** [FunAudioLLM/SenseVoice#20]
The version of FunASR should be at least 1.0.29 (the latest version is v1.1.0); 
Otherwise, it will raise a `TypeError: AutoModel.build_model() missing 1 required positional argument: 'self'` error due to changes in the `build_model` method within `funasr/auto/auto_model.py`. (FunASR PR#1858).

**Comment by LauraGPT** [comment]
Thanks.
