### ISSUE TITLE
install requirements.txt fail 

### ISSUE THREAD

**Issue by fastfading** [FunAudioLLM/SenseVoice#21]
pip install  -r requirements.txt

WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='developer.download.nvidia.com', port=443): Read timed out. (read timeout=15)")': /compute/redist/python/
ERROR: Could not find a version that satisfies the requirement python>=3.8 (from versions: none)
ERROR: No matching distribution found for python>=3.8

change the reposiory did not help

**Comment by MM-0712** [comment]
you can see the requirements.txt in details.

**Comment by mlxu995** [comment]
> pip install -r requirements.txt
> 
> WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='developer.download.nvidia.com', port=443): Read timed out. (read timeout=15)")': /compute/redist/python/ ERROR: Could not find a version that satisfies the requirement python>=3.8 (from versions: none) ERROR: No matching distribution found for python>=3.8
> 
> change the reposiory did not help

I bypass this error by manually installing each required package

**Comment by MM-0712** [comment]
python can not be installed by pip.

**Comment by mlxu995** [comment]
yes. I first create an env using conda
`conda create -n xxx python=3.10`

**Comment by LauraGPT** [comment]
Thank, we have fixed it.
