### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by huacilang** [FunAudioLLM/SenseVoice#28]
我用V100预测一个五分钟的音频报OutOfMemoryError，32G显存爆了 ，这正常吗？
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 506.00 MiB. GPU 0 has a total capacty of 31.74 GiB of which 400.88 MiB is free. Process 14974 has 31.34                              GiB memory in use. Of the allocated memory 29.76 GiB is allocated by PyTorch, and 637.51 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory i                             s large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by LauraGPT** [comment]
Please use it by funasr, with vad model.
