### ISSUE TITLE
Emotion output EMO_UNKNOWN

### ISSUE THREAD

**Issue by startreker-shzy** [FunAudioLLM/SenseVoice#31]
I have tested the emotion recognition with crema_d dataset.  But most of the output is EMO_UNKNOWN. 
![image](https://github.com/FunAudioLLM/SenseVoice/assets/78834873/4333589b-91bc-4e89-b9cb-88da9dcb7a4c)
I think It is not match the below table.
![image](https://github.com/FunAudioLLM/SenseVoice/assets/78834873/a7037ef8-a5a6-4c0e-88de-2becf29bb985)
Any threshold should be change or need finetune with emotion data?

**Comment by GizGaze** [comment]
I've got the same result with [MELD](https://github.com/declare-lab/MELD?tab=readme-ov-file) and [RAVDESS](https://www.kaggle.com/datasets/uwrfkaggler/ravdess-emotional-speech-audio) datasets. If you come across any results for SER, I would greatly appreciate it if you could share them with me.

**Comment by LauraGPT** [comment]
OK, we would check it.

**Comment by gaochangfeng** [comment]
For SER evaluation, we baned the EMO_UNK token and only score the utterance with happy, sad, angry and neutral 
We now add a `ban_emo_unk` parameter to ban it. You can upgrade the code and decode again as follow:
```
res = m.inference(
            data_in="1001_IEO_HAP_MD.wav",
            language="auto", # "zn", "en", "yue", "ja", "ko", "nospeech"
            use_itn=False,
            ban_emo_unk=True,
            **kwargs,
        )
print(res[0][0]["text"])
```
The result will be <|en|><|HAPPY|><|Speech|><|woitn|>it's eleven o'clock
