### ISSUE TITLE
Some questions about fine-tuning

### ISSUE THREAD

**Issue by srdfjy** [FunAudioLLM/SenseVoice#34]
Hi，Here are some questions about fine-tuning; I hope to receive your reply. Thank you.

1. Does it support streaming fine-tuning and inference?
2. Is the open-sourced small model trained with 8k or 16k data?
3. Can multiple 16G V100 GPUs be used for fine-tuning?

**Comment by LauraGPT** [comment]
1.Not yet.
2. 16k
3. yes

**Comment by srdfjy** [comment]
> 1.Not yet. 2. 16k 3. yes

THX.
