### ISSUE TITLE
训练数据json中 source_len是指音频文件总的帧数么？

### ISSUE THREAD

**Issue by zhoufan1978** [FunAudioLLM/SenseVoice#37]
例如
{"key": "POD0000007250_S0000518", "text_language": "<|en|>", "emo_target": "<|EMO_UNKNOWN|>", "event_target": "<|Speech|>", "with_or_wo_itn": "<|woitn|>", "target": "i use netflix but and that's not an app", "source": "/cpfs01/shared/Group-speech/beinian.lzr/data/industrial_data/english_all/audio/POD0000007250_S0000518.wav", "target_len": 9, "source_len": 180}
其中180是帧数？感觉不像时长毫秒。

**Comment by LauraGPT** [comment]
表示：帧数，一帧=10ms
