### ISSUE TITLE
执行 python .\demo_funasr.py  报错 ImportError: cannot import name 'rich_transcription_postprocess' from 'funasr.utils.postprocess_utils' 是怎么回事

### ISSUE THREAD

**Issue by anstonjie** [FunAudioLLM/SenseVoice#39]
(venv) PS E:\ai3\SenseVoice> python .\demo_funasr.py
Traceback (most recent call last):
  File "E:\ai3\SenseVoice\demo_funasr.py", line 7, in <module>
    from funasr.utils.postprocess_utils import rich_transcription_postprocess
ImportError: cannot import name 'rich_transcription_postprocess' from 'funasr.utils.postprocess_utils' (E:\ai3\SenseVoice\venv\lib\site-packages\funasr\utils\postprocess_utils.py)
(venv) PS E:\ai3\SenseVoice>

**Comment by lucasjinreal** [comment]
ImportError: cannot import name 'rich_transcription_postprocess' from 'funasr.utils.postprocess_utils'

**Comment by Snailgoo** [comment]
ImportError: cannot import name 'rich_transcription_postprocess' from 'funasr.utils.postprocess_utils'

**Comment by lucasjinreal** [comment]
@LauraGPT

**Comment by badarrrr** [comment]
ImportError: cannot import name 'rich_transcription_postprocess' from 'funasr.utils.postprocess_utils' (/root/miniconda3/lib/python3.9/site-packages/funasr/utils/postprocess_utils.py)

**Comment by v3ucn** [comment]
pip install funasr==1.1.1

**Comment by lucasjinreal** [comment]
Why not update your code but using an older funasr? I am quite unable to understand.

**Comment by v3ucn** [comment]
> Why not update your code but force users to using an older funasr? I am quite unable to understand.

I guess it's because big versions may not be backward compatible with each other

**Comment by lucasjinreal** [comment]
I guess what I mean is that why not update your code...

**Comment by lucasjinreal** [comment]
Oh, this is a mege, so I guess what I mean is why you not write `pip install funasr>=1.1.1` and attach a time when does this version comes to pypi? 

At the time I post the issue, the latest version is old.

**Comment by anstonjie** [comment]
thank you i run pip install funasr==1.1.1 is ok



At 2024-07-16 14:15:40, "刘悦" ***@***.***> wrote:

Why not update your code but force users to using an older funasr? I am quite unable to understand.

I guess it's because big versions may not be backward compatible with each other

**Comment by anstonjie** [comment]
thank you



At 2024-07-16 14:22:03, "MagicSource" ***@***.***> wrote:

Oh, this is a merge, so I guess what I mean is why you not write pip install funasr>=1.1.1 and attach a time when does this version comes to pypi?

At the time I post the issue, the latest version is old.
