### ISSUE TITLE
sensevoice-small模型推理速度与报告不符

### ISSUE THREAD

**Issue by yzslry** [FunAudioLLM/SenseVoice#42]
使用长度为9.42s的音频实际测试，encoder的推理时间就需要0.5s左右，开源的模型是报告中10s音频推理仅需70ms的模型吗？

**Comment by LauraGPT** [comment]
Please upload you wav and logfile.

**Comment by MonolithFoundation** [comment]
别用，效果奇差。和whisper差远了。
