### ISSUE TITLE
ImportError: cannot import name 'rich_transcription_postprocess' from 'funasr.utils.postprocess_utils'

### ISSUE THREAD

**Issue by lucasjinreal** [FunAudioLLM/SenseVoice#43]
ImportError: cannot import name 'rich_transcription_postprocess' from 'funasr.utils.postprocess_utils'

**Comment by badarrrr** [comment]
same error

**Comment by v3ucn** [comment]
pip install funasr==1.1.1

**Comment by lucasjinreal** [comment]
Please...... do not **always** force users to use an old lib (even thought this is your own lib) but rather than change your code to adopt the latest funasr.....
