### ISSUE TITLE
无法得到输出的每一句话的时间戳，以及标点符号

### ISSUE THREAD

**Issue by MonolithFoundation** [FunAudioLLM/SenseVoice#50]
和whisper生态稍微差一些，。

([{'key': 'wav_file_tmp_name',
   'text': '<|zh|><|HAPPY|><|Laughter|><|woitn|>我跳脱口秀大会舞吗李诞互相伤吧我还挺怀念在那个浪姐的那段时间比我是都没怎么赢过好舞输坏其拼输关至少跟我没回跟大家介绍一下赛组演对决名直晋级下题今天投票呢票票票准的本笑特别低的人但我希望我看出觉你这辈子怎多特别爱笑了今上场的十位朋已经都在被来让我们看一下他们第一组下一组长鹏一生姜子小徐组演'}],
 {'batch_data_time': 180.0, 'extract_feat': '0.136', 'load_data': '0.307'})

**Comment by bird-9** [comment]
mark

**Comment by MonolithFoundation** [comment]
关键是issue也没人鸟。
还是乖乖用whisper吧。

阿里的东西现在除了Qwen，都不太敢用。

**Comment by goIntoAction** [comment]
真没法使用，问题不少，但大部分issue都没有官方回复。貌似涉及到外语没有时间戳？目前只看到有个[项目](https://github.com/harry0703/AudioNotes) 用了paraformer-zh能拿到时间戳，有人问paraformer-en，有个官方人员说没有时间戳。对比whisper还是差了不少。

**Comment by MonolithFoundation** [comment]
你看，原作者从来不回复直接就管issue。

并不是说这个模型可以直接出时间戳，但最起码，标榜自己超越whisper，你倒是利用VAD等模型高出一个可用的东西来呀？

上来就超越whisper，结果漏字就漏大一截，都不用看时间戳不时间戳了。。

**Comment by dyyzhmm** [comment]
@MonolithFoundation  No body cares what you use!

**Comment by bltcn** [comment]
@MonolithFoundation 觉得不好可以不用

**Comment by MonolithFoundation** [comment]
牛的。。

**Comment by bird-9** [comment]
哈哈哈!
