### ISSUE TITLE
An error occurs in the demo1.py code. Please help.

### ISSUE THREAD

**Issue by ksl103177** [FunAudioLLM/SenseVoice#52]
New version available: 1.1.2. Your current version is 1.1.1.
Please use the command "pip install -U funasr" to upgrade.
2024-07-16 21:34:04,960 - modelscope - INFO - PyTorch version 2.3.1+cu118 Found.
2024-07-16 21:34:04,962 - modelscope - INFO - Loading ast index from C:\Users\user\.cache\modelscope\ast_indexer
2024-07-16 21:34:05,060 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 86c1ab7265caa4ace73adf359689f79a and a total number of 980 components indexed
Download: iic/SenseVoiceSmall failed!: cannot import name 'PreTrainedModel' from 'transformers' (unknown location)
Traceback (most recent call last):
  File "c:\SenseVoice\demo1.py", line 13, in <module>
    model = AutoModel(
  File "c:\Users\user\.conda\envs\test\lib\site-packages\funasr\auto\auto_model.py", line 124, in __init__
    model, kwargs = self.build_model(**kwargs)
  File "c:\Users\user\.conda\envs\test\lib\site-packages\funasr\auto\auto_model.py", line 218, in build_model
    assert model_class is not None, f'{kwargs["model"]} is not registered'
AssertionError: iic/SenseVoiceSmall is not registered

**Comment by LauraGPT** [comment]
Sorry, I have added two parameter:
```python
    trust_remote_code=True,
    remote_code="./model.py",
```

You could update the code and try it again.

**Comment by ksl103177** [comment]
Is it possible to also categorize speakers in that repository code, and if so, what code can I use? Please elaborate.

**Comment by LauraGPT** [comment]
> Is it possible to also categorize speakers in that repository code, and if so, what code can I use? Please elaborate.

So far, is only support in `zh`. If you want to use it in `zh`, you could ref to https://github.com/modelscope/FunASR?tab=readme-ov-file#paraformer

**Comment by ksl103177** [comment]
from funasr import AutoModel
# paraformer-zh is a multi-functional asr model
# use vad, punc, spk or not as you need
model = AutoModel(model="paraformer-zh",  vad_model="fsmn-vad",  punc_model="ct-punc", 
                  # spk_model="cam++", 
                  )
res = model.generate(input=f"{model.model_path}/example/asr_example.wav", 
                     batch_size_s=300, 
                     hotword='魔搭')
print(res)
___
Should I use this code?

**Comment by LauraGPT** [comment]
> from funasr import AutoModel
> 
> # paraformer-zh is a multi-functional asr model
> # use vad, punc, spk or not as you need
> model = AutoModel(model="paraformer-zh", vad_model="fsmn-vad", punc_model="ct-punc", # spk_model="cam++", ) res = model.generate(input=f"{model.model_path}/example/asr_example.wav", batch_size_s=300, hotword='魔搭') print(res)
> 
> Should I use this code?

model = AutoModel(model="paraformer-zh", vad_model="fsmn-vad", punc_model="ct-punc", spk_model="cam++",
)
