### ISSUE TITLE
sensevoice微调

### ISSUE THREAD

**Issue by songzhaohui12** [FunAudioLLM/SenseVoice#56]
sensevoice进行微调，如果采用自己收集的语音，对语音的频率等方面有没有要求

**Comment by songzhaohui12** [comment]
谢谢回复，我正在使用sensevoice进行微调，想让它能够识别地方方言，但我看了给出的训练jsonl示例文件，那些字段全都是必须的吗？我用一个开源的语音训练集，只使用了key,text_language,target,source四个字段,可以正常训练起来，但最终 输出的outputs感觉有点问题。主要问题如下：

**Comment by bird-9** [comment]
@songzhaohui12 Mark

**Comment by zte-tcb** [comment]
mark
