### ISSUE TITLE
sensevoice微调

### ISSUE THREAD

**Issue by songzhaohui12** [FunAudioLLM/SenseVoice#58]
我正在使用sensevoice进行微调，想让它能够识别地方方言，但我看了给出的训练jsonl示例文件，那些字段全都是必须的吗？我用一个开源的语音训练集，只使用了key,text_language,target,source四个字段,可以正常训练起来，但最终 输出的outputs感觉有点问题。主要问题如下：

1. 训练方言，text_language字段是保持<|zh|>，还是方言的标签
2. emo_target字段，提供的测试用例里面只有两种，还有其它的类别吗
3. with_or_wo_itn，这个字段我看提示在readme文件里有解释，但我也没找到
4. 对于训练集的那些字段有没有专门的yaml文件进行配置，我在源码里找了下没找到

**Comment by bird-9** [comment]
mark

**Comment by lemon3853** [comment]
mark

**Comment by LauraGPT** [comment]
We would write a details docs of how to finetune the model. Including how to get the `emo_target ` ...

**Comment by LauraGPT** [comment]
Docs of `finetune` is ready now: https://github.com/FunAudioLLM/SenseVoice?tab=readme-ov-file#finetune

**Comment by xiaomafei** [comment]
请问sensevoice2jsonl 这个工具在哪获取

**Comment by LauraGPT** [comment]
> 请问sensevoice2jsonl 这个工具在哪获取

It is a bin of funasr. If you install funasr, `sensevoice2jsonl` is install automatically.

**Comment by zte-tcb** [comment]
mark

**Comment by lukeewin** [comment]
> 我正在使用sensevoice进行微调，想让它能够识别地方方言，但我看了给出的训练jsonl示例文件，那些字段全都是必须的吗？我用一个开源的语音训练集，只使用了key,text_language,target,source四个字段,可以正常训练起来，但最终 输出的outputs感觉有点问题。主要问题如下：
> 
> 1. 训练方言，text_language字段是保持<|zh|>，还是方言的标签
> 2. emo_target字段，提供的测试用例里面只有两种，还有其它的类别吗
> 3. with_or_wo_itn，这个字段我看提示在readme文件里有解释，但我也没找到
> 4. 对于训练集的那些字段有没有专门的yaml文件进行配置，我在源码里找了下没找到

你好，请问你训练一个新语言识别模型时，这个train_text_language.txt中的标签是如何给值的，是给zh吗？还是可以自定义一个新的呢？

**Comment by lukeewin** [comment]
> 我正在使用sensevoice进行微调，想让它能够识别地方方言，但我看了给出的训练jsonl示例文件，那些字段全都是必须的吗？我用一个开源的语音训练集，只使用了key,text_language,target,source四个字段,可以正常训练起来，但最终 输出的outputs感觉有点问题。主要问题如下：
> 
> 1. 训练方言，text_language字段是保持<|zh|>，还是方言的标签
> 2. emo_target字段，提供的测试用例里面只有两种，还有其它的类别吗
> 3. with_or_wo_itn，这个字段我看提示在readme文件里有解释，但我也没找到
> 4. 对于训练集的那些字段有没有专门的yaml文件进行配置，我在源码里找了下没找到

请问训练新语种怎么可以自定义语种标识？

**Comment by wangchao112211** [comment]
能贴一下你们的环境版本么，funasr modelscope等等
