### ISSUE TITLE
运行webui.py，使用麦克风输入时，处理时间增加

### ISSUE THREAD

**Issue by Hunter6324** [FunAudioLLM/SenseVoice#65]
运行webui.py，使用麦克风输入时，处理时间增加。可以看到点击“停止后”，需要反应一段时间，录音才会出现，这期间浏览器出现“假死”现象；而使用直接使用文件输入时没有这种现象

**Comment by LauraGPT** [comment]
It is the bug of gradio, we plan to support service via wss soon.
