### ISSUE TITLE
sensevoice onnx batch推理时异常

### ISSUE THREAD

**Issue by hbk1991** [FunAudioLLM/SenseVoice#66]
sensevoice onnx单条推理时是正常的，多条同时推理时报错，这是什么情况？

![20240723-161017](https://github.com/user-attachments/assets/7c22bcc4-01ee-4e2f-9738-910c408534cd)
![20240723-161101](https://github.com/user-attachments/assets/c3c1352f-215f-49d2-acbc-1c2038a5d1e2)

**Comment by R1ckShi** [comment]
已修复，需要更新最新的funasr，并且通过源代码安装

**Comment by breath1124** [comment]
> 已修复，需要更新最新的funasr，并且通过源代码安装

你好，我刚好也遇到了这个问题，更新了funasr还是报错

**Comment by R1ckShi** [comment]
临时的修复在包发版之前需要通过funasr源代码更新，git pull之后pip install -e ./的方式

**Comment by iflamed** [comment]
为什么 `onnx runtime` 推理的时候感觉比 `torch` 更慢呢？参考下面的代码，onnx runtime 慢了8倍左右，我看也是用了GPU了。

**Use Torch**
```python
# Set the device with environment, default is cuda:0
# export SENSEVOICE_DEVICE=cuda:1

import os, re
from fastapi import FastAPI, File, Form
from fastapi.responses import HTMLResponse
from typing_extensions import Annotated
from typing import List
from enum import Enum
import torchaudio
from model import SenseVoiceSmall
from funasr.utils.postprocess_utils import rich_transcription_postprocess

class Language(str, Enum):
    auto = "auto"
    zh = "zh"
    en = "en"
    yue = "yue"
    ja = "ja"
    ko = "ko"
    nospeech = "nospeech"

model_dir = "iic/SenseVoiceSmall"
m, kwargs = SenseVoiceSmall.from_pretrained(model=model_dir, device=os.getenv("SENSEVOICE_DEVICE", "cuda:0"))
m.eval()

regex = r"<\|.*\|>"

app = FastAPI()


@app.get("/", response_class=HTMLResponse)
async def root():
    return """
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset=utf-8>
            <title>Api information</title>
        </head>
        <body>
            <a href='./docs'>Documents of API</a>
        </body>
    </html>
    """

@app.post("/api/v1/asr")
async def turn_audio_to_text(files: Annotated[List[bytes], File(description="wav or mp3 audios in 16KHz")], keys: Annotated[str, Form(description="name of each audio joined with comma")], lang: Annotated[Language, Form(description="language of audio content")] = "auto"):
    audios = []
    audio_fs = 0
    for file in files:
        data_or_path_or_list, audio_fs = torchaudio.load(file)
        data_or_path_or_list = data_or_path_or_list.mean(0)
        audios.append(data_or_path_or_list)
    if lang == "":
        lang = "auto"
    if keys == "":
        key = ["wav_file_tmp_name"]
    else:
        key = keys.split(",")
    res = m.inference(
        data_in=audios,
        language=lang, # "zh", "en", "yue", "ja", "ko", "nospeech"
        use_itn=False,
        ban_emo_unk=False,
        key=key,
        fs=audio_fs,
        **kwargs,
    )
    if len(res) == 0:
        return {"result": []}
    for it in res[0]:
        it["raw_text"] = it["text"]
        it["clean_text"] = re.sub(regex, "", it["text"], 0, re.MULTILINE)
        it["text"] = rich_transcription_postprocess(it["text"])
    return {"result": res[0]}
```

**Use Onnx Runtime**
```python
# Set the device with environment, default is cuda:0
# export SENSEVOICE_DEVICE=cuda:1

import os, re
from fastapi import FastAPI, File, Form
from fastapi.responses import HTMLResponse
from typing_extensions import Annotated
from typing import List
from enum import Enum
import torchaudio
from funasr_onnx import SenseVoiceSmall
from funasr_onnx.utils.postprocess_utils import rich_transcription_postprocess
import time

class Language(str, Enum):
    auto = "auto"
    zh = "zh"
    en = "en"
    yue = "yue"
    ja = "ja"
    ko = "ko"
    nospeech = "nospeech"

model_dir = "iic/SenseVoiceSmall"

model = SenseVoiceSmall(model_dir, batch_size=10, quantize=True, device_id=0)

regex = r"<\|.*\|>"

app = FastAPI()


@app.get("/", response_class=HTMLResponse)
async def root():
    return """
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset=utf-8>
            <title>Api information</title>
        </head>
        <body>
            <a href='./docs'>Documents of API</a>
        </body>
    </html>
    """

@app.post("/api/v1/asr")
async def turn_audio_to_text(files: Annotated[List[bytes], File(description="wav or mp3 audios in 16KHz")], keys: Annotated[str, Form(description="name of each audio joined with comma")], lang: Annotated[Language, Form(description="language of audio content")] = "auto"):
    audios = []
    audio_fs = 0
    for file in files:
        data_or_path_or_list, audio_fs = torchaudio.load(file)
        data_or_path_or_list = data_or_path_or_list.mean(0)
        audios.append(data_or_path_or_list.numpy())
    if lang == "":
        lang = "auto"
    if keys == "":
        key = ["wav_file_tmp_name"]
    else:
        key = keys.split(",")
    start_time = time.time()
    res = model(audios, language="auto", use_itn=True)
    end_time = time.time()
    print("耗时: {:.3f}秒".format(end_time - start_time))
    if len(res) == 0:
        return {"result": []}
    result = []
    for it in res:
        its = {
            "raw_text": it,
            "clean_text": re.sub(regex, "", it, 0, re.MULTILINE),
            "text": rich_transcription_postprocess(it),
        }
        result.append(its)
    return {"result": res}

```

**Comment by LauraGPT** [comment]
> 为什么 `onnx runtime` 推理的时候感觉比 `torch` 更慢呢？参考下面的代码，onnx runtime 慢了8倍左右，我看也是用了GPU了。
> 
> **Use Torch**
> 
> ```python
> # Set the device with environment, default is cuda:0
> # export SENSEVOICE_DEVICE=cuda:1
> 
> import os, re
> from fastapi import FastAPI, File, Form
> from fastapi.responses import HTMLResponse
> from typing_extensions import Annotated
> from typing import List
> from enum import Enum
> import torchaudio
> from model import SenseVoiceSmall
> from funasr.utils.postprocess_utils import rich_transcription_postprocess
> 
> class Language(str, Enum):
>     auto = "auto"
>     zh = "zh"
>     en = "en"
>     yue = "yue"
>     ja = "ja"
>     ko = "ko"
>     nospeech = "nospeech"
> 
> model_dir = "iic/SenseVoiceSmall"
> m, kwargs = SenseVoiceSmall.from_pretrained(model=model_dir, device=os.getenv("SENSEVOICE_DEVICE", "cuda:0"))
> m.eval()
> 
> regex = r"<\|.*\|>"
> 
> app = FastAPI()
> 
> 
> @app.get("/", response_class=HTMLResponse)
> async def root():
>     return """
>     <!DOCTYPE html>
>     <html>
>         <head>
>             <meta charset=utf-8>
>             <title>Api information</title>
>         </head>
>         <body>
>             <a href='./docs'>Documents of API</a>
>         </body>
>     </html>
>     """
> 
> @app.post("/api/v1/asr")
> async def turn_audio_to_text(files: Annotated[List[bytes], File(description="wav or mp3 audios in 16KHz")], keys: Annotated[str, Form(description="name of each audio joined with comma")], lang: Annotated[Language, Form(description="language of audio content")] = "auto"):
>     audios = []
>     audio_fs = 0
>     for file in files:
>         data_or_path_or_list, audio_fs = torchaudio.load(file)
>         data_or_path_or_list = data_or_path_or_list.mean(0)
>         audios.append(data_or_path_or_list)
>     if lang == "":
>         lang = "auto"
>     if keys == "":
>         key = ["wav_file_tmp_name"]
>     else:
>         key = keys.split(",")
>     res = m.inference(
>         data_in=audios,
>         language=lang, # "zh", "en", "yue", "ja", "ko", "nospeech"
>         use_itn=False,
>         ban_emo_unk=False,
>         key=key,
>         fs=audio_fs,
>         **kwargs,
>     )
>     if len(res) == 0:
>         return {"result": []}
>     for it in res[0]:
>         it["raw_text"] = it["text"]
>         it["clean_text"] = re.sub(regex, "", it["text"], 0, re.MULTILINE)
>         it["text"] = rich_transcription_postprocess(it["text"])
>     return {"result": res[0]}
> ```
> 
> **Use Onnx Runtime**
> 
> ```python
> # Set the device with environment, default is cuda:0
> # export SENSEVOICE_DEVICE=cuda:1
> 
> import os, re
> from fastapi import FastAPI, File, Form
> from fastapi.responses import HTMLResponse
> from typing_extensions import Annotated
> from typing import List
> from enum import Enum
> import torchaudio
> from funasr_onnx import SenseVoiceSmall
> from funasr_onnx.utils.postprocess_utils import rich_transcription_postprocess
> import time
> 
> class Language(str, Enum):
>     auto = "auto"
>     zh = "zh"
>     en = "en"
>     yue = "yue"
>     ja = "ja"
>     ko = "ko"
>     nospeech = "nospeech"
> 
> model_dir = "iic/SenseVoiceSmall"
> 
> model = SenseVoiceSmall(model_dir, batch_size=10, quantize=True, device_id=0)
> 
> regex = r"<\|.*\|>"
> 
> app = FastAPI()
> 
> 
> @app.get("/", response_class=HTMLResponse)
> async def root():
>     return """
>     <!DOCTYPE html>
>     <html>
>         <head>
>             <meta charset=utf-8>
>             <title>Api information</title>
>         </head>
>         <body>
>             <a href='./docs'>Documents of API</a>
>         </body>
>     </html>
>     """
> 
> @app.post("/api/v1/asr")
> async def turn_audio_to_text(files: Annotated[List[bytes], File(description="wav or mp3 audios in 16KHz")], keys: Annotated[str, Form(description="name of each audio joined with comma")], lang: Annotated[Language, Form(description="language of audio content")] = "auto"):
>     audios = []
>     audio_fs = 0
>     for file in files:
>         data_or_path_or_list, audio_fs = torchaudio.load(file)
>         data_or_path_or_list = data_or_path_or_list.mean(0)
>         audios.append(data_or_path_or_list.numpy())
>     if lang == "":
>         lang = "auto"
>     if keys == "":
>         key = ["wav_file_tmp_name"]
>     else:
>         key = keys.split(",")
>     start_time = time.time()
>     res = model(audios, language="auto", use_itn=True)
>     end_time = time.time()
>     print("耗时: {:.3f}秒".format(end_time - start_time))
>     if len(res) == 0:
>         return {"result": []}
>     result = []
>     for it in res:
>         its = {
>             "raw_text": it,
>             "clean_text": re.sub(regex, "", it, 0, re.MULTILINE),
>             "text": rich_transcription_postprocess(it),
>         }
>         result.append(its)
>     return {"result": res}
> ```

Ref to https://github.com/FunAudioLLM/SenseVoice/issues/76

**Comment by hbk1991** [comment]
> > 已修复，需要更新最新的funasr，并且通过源代码安装
> 
> 你好，我刚好也遇到了这个问题，更新了funasr还是报错

![img_v3_02dm_46582a17-4113-471a-a2e8-b57db0142f0g](https://github.com/user-attachments/assets/9f7a5d25-ca6c-42e7-821d-b62bed7893b7)
我修改了funasr_onnx/sensevoice_bin.py，就ok了(然后在输出时，把batch内的每个query结果也分开)

**Comment by hbk1991** [comment]
> > 已修复，需要更新最新的funasr，并且通过源代码安装
> 
> 你好，我刚好也遇到了这个问题，更新了funasr还是报错

![img_v3_02dn_0d64153c-aeed-4725-bab0-29fa4063d28g](https://github.com/user-attachments/assets/d2879de7-468c-4183-802f-ecd10d686706)
修改funasr_onnx/sensevoice_bin.py里面这几行，就可以了。

**Comment by R1ckShi** [comment]
这种小型修复需要通过源码安装，现在最新的代码已经不是这张图里面原来的代码了
```
feats, feats_len = self.extract_feat(waveform_list[beg_idx:end_idx])
            _language_list = language_list[beg_idx:end_idx]
            _textnorm_list = textnorm_list[beg_idx:end_idx]
            if not len(_language_list):
                _language_list = [language_list[0]]
                _textnorm_list = [textnorm_list[0]]
            B = feats.shape[0]
            if len(_language_list) == 1 and B != 1:
                _language_list = _language_list * B
            if len(_textnorm_list) == 1 and B != 1:
                _textnorm_list = _textnorm_list * B
            ctc_logits, encoder_out_lens = self.infer(
                feats,
                feats_len,
                np.array(_language_list, dtype=np.int32),
                np.array(_textnorm_list, dtype=np.int32),
            )
```
