### ISSUE TITLE
libtorch推理问题

### ISSUE THREAD

**Issue by breath1124** [FunAudioLLM/SenseVoice#68]
在使用readme中给的libtorch导出示例时，遇到如下报错

![20240725-143434](https://github.com/user-attachments/assets/cdea9473-f6a6-4ccd-82d7-1fb4545dd0e2)

![20240725-143419](https://github.com/user-attachments/assets/8c498e69-2af0-4a47-97da-439006ff6ef2)

**Comment by R1ckShi** [comment]
已经修复，请拉取最新的funasr代码
注意这种临时修复需要确保funasr库是通过github源码`pip install -e ./`安装的，git pull即可生效

**Comment by breath1124** [comment]
> 已经修复，请拉取最新的funasr代码 注意这种临时修复需要确保funasr库是通过github源码`pip install -e ./`安装的，git pull即可生效

目前libtorch支持多条推理吗，batch_size设置为10，当wav_or_scp中不止一条数据时，只能推理得到第一条数据的结果


![20240725-175407](https://github.com/user-attachments/assets/547f63f4-3e60-4995-b4a9-4e88824a54b6)
![20240725-175347](https://github.com/user-attachments/assets/51655f9b-dc7f-4abb-8b87-4d769becc0d6)

**Comment by R1ckShi** [comment]
> > 已经修复，请拉取最新的funasr代码 注意这种临时修复需要确保funasr库是通过github源码`pip install -e ./`安装的，git pull即可生效
> 
> 目前libtorch支持多条推理吗，batch_size设置为10，当wav_or_scp中不止一条数据时，只能推理得到第一条数据的结果
> 
> ![20240725-175407](https://private-user-images.githubusercontent.com/42616564/352061539-547f63f4-3e60-4995-b4a9-4e88824a54b6.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NjA2MDksIm5iZiI6MTcyMTk2MDMwOSwicGF0aCI6Ii80MjYxNjU2NC8zNTIwNjE1MzktNTQ3ZjYzZjQtM2U2MC00OTk1LWI0YTktNGU4ODgyNGE1NGI2LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQwMjE4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZWYzOGY4YmRlYTU1ODhmOTI4YTk5MTE4NDM2MGM1NDM0NmIyN2QwNzQ1MTU2OTVjYWI3YzFjZTlkNDZiYWI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LdQ0Yxk9i48dJJKsM43hLV5-H3XZ-8mxhy-wJ5CjYT8) ![20240725-175347](https://private-user-images.githubusercontent.com/42616564/352061554-51655f9b-dc7f-4abb-8b87-4d769becc0d6.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NjA2MDksIm5iZiI6MTcyMTk2MDMwOSwicGF0aCI6Ii80MjYxNjU2NC8zNTIwNjE1NTQtNTE2NTVmOWItZGM3Zi00YWJiLThiODctNGQ3NjliZWNjMGQ2LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQwMjE4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTM3MTljNzRmMWZiMjVmMWQ4N2M5ZDFlNDg3NGUyZWU1MzJjYmU5NzllZGNhYzNjNDllMjk4Y2RlOGQxZjFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1G1J-g_sa081hnKyO-J79phd0GyXy-fs4dXqqRcYL9A)
已修复

**Comment by breath1124** [comment]
> > > 已经修复，请拉取最新的funasr代码 注意这种临时修复需要确保funasr库是通过github源码`pip install -e ./`安装的，git pull即可生效
> > 
> > 
> > 目前libtorch支持多条推理吗，batch_size设置为10，当wav_or_scp中不止一条数据时，只能推理得到第一条数据的结果
> > ![20240725-175407](https://private-user-images.githubusercontent.com/42616564/352061539-547f63f4-3e60-4995-b4a9-4e88824a54b6.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NjA2MDksIm5iZiI6MTcyMTk2MDMwOSwicGF0aCI6Ii80MjYxNjU2NC8zNTIwNjE1MzktNTQ3ZjYzZjQtM2U2MC00OTk1LWI0YTktNGU4ODgyNGE1NGI2LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQwMjE4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZWYzOGY4YmRlYTU1ODhmOTI4YTk5MTE4NDM2MGM1NDM0NmIyN2QwNzQ1MTU2OTVjYWI3YzFjZTlkNDZiYWI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LdQ0Yxk9i48dJJKsM43hLV5-H3XZ-8mxhy-wJ5CjYT8) ![20240725-175347](https://private-user-images.githubusercontent.com/42616564/352061554-51655f9b-dc7f-4abb-8b87-4d769becc0d6.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NjA2MDksIm5iZiI6MTcyMTk2MDMwOSwicGF0aCI6Ii80MjYxNjU2NC8zNTIwNjE1NTQtNTE2NTVmOWItZGM3Zi00YWJiLThiODctNGQ3NjliZWNjMGQ2LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQwMjE4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTM3MTljNzRmMWZiMjVmMWQ4N2M5ZDFlNDg3NGUyZWU1MzJjYmU5NzllZGNhYzNjNDllMjk4Y2RlOGQxZjFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1G1J-g_sa081hnKyO-J79phd0GyXy-fs4dXqqRcYL9A)
> > 已修复

还有一个问题，如果传入的wav_or_scp列表长度大于设置的batch_size会出现如下报错。
目前我把数据这样分段传入才能正常运行。
`def process_batches(file_list, batch_size):
    for i in range(0, len(file_list), batch_size):
        yield file_list[i:i + batch_size]

for batch in process_batches(file_names, batch_size):
    res = model(
        wav_content=batch,
        language="auto", 
        use_itn=True,
        batch_size=batch_size
    )`

![screenshot-20240726-111156](https://github.com/user-attachments/assets/c25306bd-e568-4328-8308-00dfe6d52cb2)

**Comment by R1ckShi** [comment]
修复了，这里因为要同时处理一个language id扩展为多条或者与wav长度一致的language list的情况，有些情况没有考虑全面

**Comment by breath1124** [comment]
> 修复了，这里因为要同时处理一个language id扩展为多条或者与wav长度一致的language list的情况，有些情况没有考虑全面

还有两个问题想问一下
1、在model = SenseVoiceSmall(model_dir, batch_size=batch_size, device="cuda:3")这行代码中，如果我指定的device和之前保存为libtorch时候的device不一致，会出现下图中的报错
2、为什么在batch_size一样的时候，推理速度会比使用demo1中的代码慢两倍多，我的batch_size设置为32，共1500条音频，每条音频长度为10秒，demo1的推理速度30秒左右，libtorch推理速度70秒左右

![20240726-130717](https://github.com/user-attachments/assets/853f68da-6e7c-46bd-8756-633fe1480a79)

**Comment by R1ckShi** [comment]
第一个问题是libtorch的特性，在哪里用就要在哪里导出
第二个问题我确实不清楚，不过最快的方式应该是使用int8的onnx，即在demo_onnx中打开quantize，使用c++推理，当然python也可以

**Comment by LauraGPT** [comment]
`demo1.py` is faster due to the `vad_model` and batching by sorted vad_slices. Maybe you could ref to https://github.com/modelscope/FunASR/blob/main/funasr/auto/auto_model.py#L329
