### ISSUE TITLE
指定识别语音为中文，但是经常出现日文和英文，怎么解决

### ISSUE THREAD

**Issue by crystone123** [FunAudioLLM/SenseVoice#72]
Notice: In order to resolve issues more efficiently, please raise issue following the template.
（注意：为了更加高效率解决您遇到的问题，请按照模板提问，补充细节）

## ❓ Questions and Help

按照官方示例代码，model.generate接口指定中文参数，language="zn"。用得Funasr的实时语音识别方式，会出现日文和英文的情况。

代码如下：
model_dir = "iic/SenseVoiceSmall"
model = AutoModel(
    model=model_dir,
    trust_remote_code=True,
)
files = os.listdir(path)
store = []
run_time = []
for file in files:
    try:
        file_name = os.path.basename(file)
        st = time.time()
        chunk_stride = chunk_size[1] * 960 # 600ms
        speech, sample_rate = soundfile.read("voice_test/" + file_name)
        cache = {}
        total_chunk_num = int(len((speech)-1)/chunk_stride+1)
        res_str = ""
        for i in range(total_chunk_num):
            speech_chunk = speech[i*chunk_stride:(i+1)*chunk_stride]
            is_final = i == total_chunk_num - 1
            res = model.generate(
                input=speech_chunk,
                cache={},
                language="zn", # "zn", "en", "yue", "ja", "ko", "nospeech"
                use_itn=False,
                temperature = 0.01,
            )
            final_res = post_processing(rich_transcription_postprocess(res[0]["text"]))
            run_time.append(time.time()-st)
            print(final_res)
            res_str = res_str + final_res
            print("耗时为{}".format(time.time()-st))
    except Exception:
        print(f"发生了异常{file_name}")

请问有大神知道是为什么吗，还是说sensevoice不支持funasr的实时语音识别。谢谢

**Comment by LauraGPT** [comment]
SenseVoice is non-streaming model. We would release new streaming model in future.

**Comment by csukuangfj** [comment]
## sense voice 的流式/实时语音识别， 视频 demo
- [115: 新一代Kaldi + RK3588 + SenseVoice + 本地实时语音识别(CPU)](https://www.bilibili.com/video/BV1zrEFzFECg/)
- [113. 新一代 Kaldi: 使用SenseVoice+VAD进行实时语音识别(CPU)](https://www.bilibili.com/video/BV1xcEMz8EsX/)
- [116. 新一代Kaldi: 安卓+实时本地语音识别+非流式SenseVoice](https://www.bilibili.com/video/BV1VqEvzSEcs/)

## 开源代码
- [sense-voice-simulate-streaming-alsa-cxx-api.cc](https://github.com/k2-fsa/sherpa-onnx/blob/master/cxx-api-examples/sense-voice-simulate-streaming-alsa-cxx-api.cc)
- [sense-voice-simulate-streaming-microphone-cxx-api.cc](https://github.com/k2-fsa/sherpa-onnx/blob/master/cxx-api-examples/sense-voice-simulate-streaming-microphone-cxx-api.cc)
- [simulate-streaming-sense-voice-microphone.py](https://github.com/k2-fsa/sherpa-onnx/blob/master/python-api-examples/simulate-streaming-sense-voice-microphone.py)
- [SherpaOnnxSimulateStreamingAsr](https://github.com/k2-fsa/sherpa-onnx/tree/master/android/SherpaOnnxSimulateStreamingAsr)

## 编译好的 apk
https://k2-fsa.github.io/sherpa/onnx/android/apk-simulate-streaming-asr-cn.html

|1|2|
|---|---|
|<img width="1350" alt="Image" src="https://github.com/user-attachments/assets/aa6a0bfd-0f56-49f0-9f4e-e31e713e981c" />|<img width="1191" alt="Image" src="https://github.com/user-attachments/assets/d7013668-6c89-4add-8675-04267fbdc759" />|

**Comment by andyuan1000** [comment]
还是有此问题
