### ISSUE TITLE
AED 能力较差时训练数据不足吗

### ISSUE THREAD

**Issue by wuhongsheng** [FunAudioLLM/SenseVoice#91]

**Comment by gaochangfeng** [comment]
模型在训练时只使用了ASR的数据和少量的负样本噪声数据，没有专门在aed任务上训练

**Comment by wuhongsheng** [comment]
> 模型在训练时只使用了ASR的数据和少量的负样本噪声数据，没有专门在aed任务上训练

按我可以基于开源数据做微调训练来扩充事件类型吗

**Comment by gaochangfeng** [comment]
sensevoice预留了未使用的token，可以使用这些token进行事件类别扩展

**Comment by wuhongsheng** [comment]
> sensevoice预留了未使用的token，可以使用这些token进行事件类别扩展

预留词表在哪里看

**Comment by gaochangfeng** [comment]
调用tokenizer的成员函数，具体方式请查看源码

**Comment by wuhongsheng** [comment]
> 调用tokenizer的成员函数，具体方式请查看源码
看了接口没有发现可以获取unused 的ids
![image](https://github.com/user-attachments/assets/72336b62-95c0-415e-b8f8-aa8f713cf446)

**Comment by gaochangfeng** [comment]
```[tokenizer.ids2tokens(idx) for idx in range(tokenizer.get_vocab_size()) ]```, 未使用的token被命名为SPECIAL_TOKEN_X, 建议使用SPECIAL_TOKEN_15之后的token进行扩展

**Comment by wuhongsheng** [comment]
> [tokenizer.ids2tokens(idx) for idx in range(tokenizer.get_vocab_size()) ]
好的，感谢

**Comment by wuhongsheng** [comment]
> `[tokenizer.ids2tokens(idx) for idx in range(tokenizer.get_vocab_size()) ]`, 未使用的token被命名为SPECIAL_TOKEN_X, 建议使用SPECIAL_TOKEN_15之后的token进行扩展

我用ESC-50 AED能力的话，训练数据里面target和target_len应该怎么设

**Comment by gaochangfeng** [comment]
与asr格式相同，语种设为nospeech，情感是为emo_unk, 事件设为目标事件对应的token 文本设为空

**Comment by wuhongsheng** [comment]
> 与asr格式相同，语种设为nospeech，情感是为emo_unk, 事件设为目标事件对应的token 文本设为空

训练报错
![image](https://github.com/user-attachments/assets/879c2827-0ca9-4bae-b608-dbb52a7fcad6)

**Comment by wuhongsheng** [comment]
已解决，有个token 写错了

**Comment by wuhongsheng** [comment]
在ESC-50数据集上扩展7个事件类型，验证精度明显提升
![image](https://github.com/user-attachments/assets/9b5ab898-099c-4ffa-af82-648bd8cf0944)

**Comment by heheda166** [comment]
@wuhongsheng 请问下您在扩充事件时 是用的已有的token，如：<|SPECIAL_TOKEN_16|>，还是改成了对应的事件名呢，如：<|火车轰鸣声|>
